import { useEffect, useMemo, useState } from 'react';
import { Activity, Bot, ChevronDown, Clock3, Coins, Gauge, Pause, Play, Radio, RefreshCw, ShieldAlert, Square, Terminal, Wallet, X } from 'lucide-react';
import type { ControlAction, DashboardState } from './types';

type PortfolioPoint = { ts: number; valueUsdt: number };
type PortfolioRange = '15m' | '1h' | '24h' | '7d' | 'all';
const portfolioRanges: PortfolioRange[] = ['15m', '1h', '24h', '7d', 'all'];
const mergePoints = (...groups: PortfolioPoint[][]) => {
 const byTime = new Map<number, PortfolioPoint>();
 groups.flat().forEach(point => { if (Number.isFinite(point.ts) && Number.isFinite(point.valueUsdt)) byTime.set(point.ts, point); });
 return [...byTime.values()].sort((a,b)=>a.ts-b.ts);
};

const demo: DashboardState = {
  mode:'paper', paused:false, stopped:false, liquidationPending:false,
  health:{feedConnected:false,lastTickTs:0,jevReady:false,reviewerReady:false},
  balances:{availableUsdt:10,holdings:[],portfolioUsdt:10,realisedPnlUsdt:0,unrealisedPnlUsdt:0,feesUsdt:0,drawdownPercent:0,openPositions:0},
  usage:{jev:{inputTokens:0,outputTokens:0,costUsd:0,requests:0},openai:{inputTokens:0,outputTokens:0,costUsd:0,requests:0},totalCostUsd:0},
  caps:{floatUsdt:10,maxOrderUsdt:.2,dailyLossStopUsdt:1,dailyApiSpendUsd:1,maxHoldSeconds:900,maxPositions:1},
  strategy:{version:1,entryConfidence:.85,continuationProbability:.8,reversalExitProbability:.75,costBufferBps:15,targetHoldSeconds:120,positionFraction:.02,selectedSymbols:[]},
  latestReview:'',openOrders:[],recentTrades:[],recentEvents:[],skippedReasons:{},metrics:{decisions:0,approved:0,avgDecisionLatencyMs:0},candidateCount:0,updatedAt:Date.now()
};
const cash=(n:number,code='USDT',minimumFractionDigits=2)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:code==='USDT'?'USD':code,minimumFractionDigits,maximumFractionDigits:minimumFractionDigits===2?2:6}).format(n).replace('US$','＄');
const reasonLabels:Record<string,string>={paused:'Bot paused',position_limit:'Maximum open positions reached',daily_loss_stop:'Daily loss limit reached',api_spend_stop:'Daily API spend limit reached',stale_data:'Market or JEV data is stale',stale_book:'Order book data is stale',symbol_unavailable:'Symbol unavailable for trading',not_selected:'Symbol is outside the selected strategy set',invalid_book:'Invalid bid and ask prices',liquidity:'Liquidity or spread requirements not met',insufficient_usdt:'Insufficient USDT for order',below_exchange_minimum:'Order is below the exchange minimum',jev_threshold:'JEV confidence below strategy threshold',unproven_net_edge:'Net trading edge is not established',jev_error:'JEV assessment failed'};
const reasonLabel=(reason:string)=>reasonLabels[reason]??reason.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const num=(n:number,d=2)=>new Intl.NumberFormat('en-AU',{maximumFractionDigits:d}).format(n);
const ago=(ts:number)=>{const s=Math.max(0,Math.floor((Date.now()-ts)/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};

export default function App(){
 const [state,setState]=useState<DashboardState>(demo),[connected,setConnected]=useState(false),[isDemo,setDemo]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[capsOpen,setCapsOpen]=useState(false),[liquidateOpen,setLiquidateOpen]=useState(false),[caps,setCaps]=useState(demo.caps),[now,setNow]=useState(Date.now());
 const [portfolioRange,setPortfolioRange]=useState<PortfolioRange>('24h'),[portfolioPoints,setPortfolioPoints]=useState<PortfolioPoint[]>([]),[portfolioLoading,setPortfolioLoading]=useState(true);
 useEffect(()=>{let alive=true;const apply=(data:string)=>{try{const x=JSON.parse(data) as DashboardState;if(x?.balances&&x?.health){setState(x);setCaps(x.caps);setDemo(false);setConnected(true);setPortfolioPoints(points=>mergePoints(points,[{ts:x.updatedAt,valueUsdt:x.balances.portfolioUsdt}]))}}catch{}};const poll=()=>fetch('/api/state').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>apply(JSON.stringify(x))).catch(()=>alive&&setConnected(false));poll();const es=new EventSource('/api/events');es.addEventListener('state',e=>apply((e as MessageEvent).data));es.onopen=()=>alive&&setConnected(true);es.onerror=()=>alive&&setConnected(false);const p=window.setInterval(poll,15000),t=window.setInterval(()=>setNow(Date.now()),10000);return()=>{alive=false;es.close();clearInterval(p);clearInterval(t)}},[]);
 useEffect(()=>{let alive=true;const pollPortfolio=()=>fetch(`/api/portfolio?range=${portfolioRange}`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{points:PortfolioPoint[]}>}).then(data=>{if(alive&&Array.isArray(data.points)){const history=mergePoints(data.points);setPortfolioPoints(previous=>{const latest=previous[previous.length-1];const liveTail=latest&&(!history.length||latest.ts>history[history.length-1].ts)?[latest]:[];return mergePoints(history,liveTail)});setPortfolioLoading(false)}}).catch(()=>{if(alive)setPortfolioLoading(false)});setPortfolioLoading(true);pollPortfolio();const timer=window.setInterval(pollPortfolio,20000);return()=>{alive=false;clearInterval(timer)}},[portfolioRange]);
 const age=useMemo(()=>Math.max(0,Math.floor((now-state.updatedAt)/1000)),[now,state.updatedAt]);
 const health=[state.health.feedConnected?'Feed online':'Feed offline',state.health.jevReady?'JEV ready':'JEV unavailable',state.health.reviewerReady?'Reviewer ready':'Reviewer unavailable'];
 async function control(action:ControlAction){setSaving(true);setNotice('');try{const body=action==='set-caps'?{action,caps}:{action};const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`Request failed (${r.status})`);setNotice(action==='set-caps'?'Risk limits updated':`Bot ${action==='stop'?'stopped':action==='pause'?'paused':'resumed'}`)}catch(e){setNotice(e instanceof Error?e.message:'Control request failed')}finally{setSaving(false);setCapsOpen(false);setTimeout(()=>setNotice(''),3500)}}
 async function liquidate(){setSaving(true);setNotice('');try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'liquidate'})});if(!r.ok)throw Error('Liquidation request failed');const next=await r.json() as DashboardState;setState(next);setNotice(next.liquidationPending?'Liquidation queued until a fresh bid arrives':'Paper holdings sold for USDT; trading paused')}catch(e){setNotice(e instanceof Error?e.message:'Liquidation request failed')}finally{setSaving(false);setLiquidateOpen(false);setTimeout(()=>setNotice(''),3500)}}
 const service=(title:string,s:DashboardState['usage']['jev'])=><div className="service-row"><div className="service-title"><i>{title==='JEV'?'J':<Bot size={16}/>}</i><div><b>{title}</b><small><span className={`dot ${title==='JEV'?(state.health.jevReady?'green':''):(state.health.reviewerReady?'green':'')}`}/>{title==='JEV'?(state.health.jevReady?'Ready':'Offline'):(state.health.reviewerReady?'Ready':'Offline')}</small></div></div><div><small>Requests</small><b>{s.requests}</b></div><div><small>Tokens in / out</small><b>{num(s.inputTokens,0)} / {num(s.outputTokens,0)}</b></div><div><small>Spend</small><b>{cash(s.costUsd,'USD',4)}</b></div></div>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={18}/></span><span><b>JEV trading bot</b><small>TRADING OPS</small></span></div><div className="workspace"><span className="workspace-icon">J</span><span><b>JEV trading bot</b><small>Personal workspace</small></span><ChevronDown size={14}/></div><div className="nav-label">MONITOR</div><nav><a className="active"><Gauge size={17}/>Overview</a><a><Activity size={17}/>Markets</a><a><Coins size={17}/>Positions</a><a><Terminal size={17}/>Activity log</a></nav><div className="sidebar-bottom"><div className="sidebar-status"><span className={`dot ${connected?'green':''}`}/><span><b>{connected?'API connected':'Waiting for API'}</b><small>{isDemo?'Default config only':'Live state stream'}</small></span></div><div className="user"><span className="avatar">HS</span><span><b>Henry Simpson</b><small>Operator</small></span></div></div></aside>
 <main className="main"><header className="topbar"><div>Workspace <i>/</i> <b>Overview</b></div><div className="top-actions"><span className="stream"><span className={`dot ${connected?'green':''}`}/>{connected?'Streaming':'Reconnecting'} · {age}s</span><button className="icon-btn" onClick={()=>fetch('/api/state').then(r=>r.json()).then(setState).catch(()=>setConnected(false))}><RefreshCw size={16}/></button><span className="avatar">HS</span></div></header><div className="content">
 {isDemo&&<div className="demo"><Radio size={15}/><b>Backend offline</b><span>Showing default configuration. Live balances, usage and controls need the backend.</span></div>}
 <section className="heading"><div><small className="eyebrow">TRADING OPERATIONS</small><h1>Trading overview</h1><p>Portfolio performance and bot health at a glance.</p></div><div className="head-pills"><span className="pill mode"><i/> {state.mode} mode</span><span className="pill health"><i/> {health.join(' · ')}</span></div></section>
 <section className="metrics"><Metric label="Portfolio value" value={cash(state.balances.portfolioUsdt)} icon={<Wallet size={16}/>} large/><Metric label="Realised P&L" value={cash(state.balances.realisedPnlUsdt)} positive={state.balances.realisedPnlUsdt>=0} icon={<Activity size={16}/>}/><Metric label="Unrealised P&L" value={cash(state.balances.unrealisedPnlUsdt)} positive={state.balances.unrealisedPnlUsdt>=0} icon={<Activity size={16}/>}/><Metric label="Fees paid" value={cash(state.balances.feesUsdt)} icon={<Coins size={16}/>}/><Metric label="Drawdown" value={`${num(state.balances.drawdownPercent)}%`} icon={<ShieldAlert size={16}/>}/></section>
 <PortfolioChart points={portfolioPoints} range={portfolioRange} onRange={setPortfolioRange} loading={portfolioLoading} currentValue={state.balances.portfolioUsdt}/>
 <div className="grid"><section className="panel"><PanelTitle title="Balances & holdings" meta={`${state.balances.holdings.length+1} ${state.balances.holdings.length?'assets':'asset'}`}/><div className="holding row"><span className="token usdt">₮</span><span><b>USDT</b><small>Available balance</small></span><span className="right"><b>{num(state.balances.availableUsdt)}</b><small>Stablecoin float</small></span></div>{state.balances.holdings.map(h=><div className="holding row" key={h.symbol}><span className="token">{h.symbol.slice(0,1)}</span><span><b>{h.symbol}</b><small>{num(h.quantity,6)} units · entry {cash(h.entryPrice)}</small></span><span className="right"><b>{cash(h.valueUsdt)}</b><small>Held {num(h.ageSeconds/60,0)}m</small></span></div>)}<div className="holding-foot"><span>Open positions</span><b>{state.balances.openPositions} / {state.caps.maxPositions}</b></div></section>
 <section className="panel"><PanelTitle title="API usage & spend" meta="Current day"/>{service('JEV',state.usage.jev)}{service('OpenAI',state.usage.openai)}<div className="total-spend"><span>Total API spend</span><b>{cash(state.usage.totalCostUsd,'USD',4)}</b><small>Daily cap {cash(state.caps.dailyApiSpendUsd,'USD')}</small></div></section>
 <section className="panel"><PanelTitle title="Open orders" meta={`${state.openOrders.length} active`}/><div className="table-wrap"><table><thead><tr><th>Market</th><th>Side</th><th>Price</th><th>Amount</th><th>Placed</th></tr></thead><tbody>{state.openOrders.length?state.openOrders.map(o=><tr key={o.id}><td><b>{o.symbol}</b><small>{o.id}</small></td><td><em className={o.side.toLowerCase()}>{o.side}</em></td><td>{cash(o.price)}</td><td>{num(o.quantity,6)}</td><td>{ago(o.ts)}</td></tr>):<tr><td colSpan={5} className="empty">No open orders</td></tr>}</tbody></table></div></section>
 <section className="panel review"><PanelTitle title="Latest review" meta="Strategy reviewer"/><div className="review-copy"><span className="review-icon"><Bot size={17}/></span><p>{state.latestReview||'No review has been recorded yet.'}</p></div><small className="review-foot"><Clock3 size={13}/> Updated {ago(state.updatedAt)}</small></section>
 <section className="panel"><PanelTitle title="Recent trades" meta={`${state.recentTrades.length} latest`}/><div className="table-wrap"><table><thead><tr><th>Market</th><th>Side</th><th>Price</th><th>Notional</th><th>Fee</th><th>Time</th></tr></thead><tbody>{state.recentTrades.length?state.recentTrades.map(t=><tr key={t.id}><td><b>{t.symbol}</b><small>{t.reason}</small></td><td><em className={t.side.toLowerCase()}>{t.side}</em></td><td>{cash(t.price)}</td><td>{cash(t.notionalUsdt)}</td><td>{cash(t.feeUsdt)}</td><td>{ago(t.ts)}</td></tr>):<tr><td colSpan={6} className="empty">No recent trades</td></tr>}</tbody></table></div></section>
 <section className="panel strategy"><PanelTitle title="Strategy & risk" meta={`Version ${state.strategy.version}`} action="Edit limits" onAction={()=>setCapsOpen(true)}/><div className="strategy-name"><span className="strategy-icon"><Activity size={17}/></span><div><b>Active strategy</b><small>{state.strategy.selectedSymbols.join(' · ')}</small></div></div><div className="params"><Param label="Entry confidence" value={num(state.strategy.entryConfidence*100,0)+'%'}/><Param label="Continuation" value={num(state.strategy.continuationProbability*100,0)+'%'}/><Param label="Reversal exit" value={num(state.strategy.reversalExitProbability*100,0)+'%'}/><Param label="Cost buffer" value={`${num(state.strategy.costBufferBps,0)} bps`}/><Param label="Target hold" value={`${num(state.strategy.targetHoldSeconds/60,0)} min`}/><Param label="Position fraction" value={`${num(state.strategy.positionFraction*100,1)}%`}/></div><div className="risk"><b>Risk limits</b><span>Float <strong>{cash(state.caps.floatUsdt)}</strong></span><span>Max order <strong>{cash(state.caps.maxOrderUsdt)}</strong></span><span>Daily loss stop <strong>{cash(state.caps.dailyLossStopUsdt)}</strong></span><span>Max positions <strong>{state.caps.maxPositions}</strong></span><span>Max hold <strong>{num(state.caps.maxHoldSeconds/60,0)} min</strong></span><span>Daily API spend <strong>{cash(state.caps.dailyApiSpendUsd,'USD')}</strong></span></div></section>
 <section className="panel"><PanelTitle title="Skipped signals" meta="Current session"/><div className="skips">{Object.entries(state.skippedReasons).length?Object.entries(state.skippedReasons).map(([why,count])=><div key={why}><span><X size={12}/>{reasonLabel(why)}</span><b>{count}</b></div>):<p className="empty">No skipped signals recorded.</p>}</div><div className="skip-note">{state.metrics.approved} approved of {state.metrics.decisions} decisions · {Math.round(state.metrics.avgDecisionLatencyMs)}ms average · {state.candidateCount} candidates</div></section></div>
 <footer>JEV trading bot · State age {age}s · {isDemo?'Backend offline':'Connected backend'}</footer></div></main>
 <div className="dock"><div><span className={`dot ${state.health.feedConnected?'green':''}`}/><span><b>Bot controls</b><small>{state.liquidationPending?'Liquidation pending':state.stopped?'Stopped':state.paused?'Paused':state.mode==='live'?'Live trading':'Paper trading'}</small></span></div><div className="dock-buttons"><button className={state.paused?'resume':''} aria-label={state.paused?'Resume trading':'Pause trading'} disabled={saving||isDemo||state.stopped||state.liquidationPending} onClick={()=>control(state.paused?'resume':'pause')}>{state.paused?<Play size={14}/>:<Pause size={14}/>}<span>{state.paused?'Resume trading':'Pause trading'}</span></button><button className="liquidate" aria-label="Liquidate paper holdings" disabled={saving||isDemo||state.liquidationPending||(!state.balances.holdings.length&&!state.openOrders.length)} onClick={()=>setLiquidateOpen(true)}><Coins size={14}/><span>Liquidate</span></button><button className="kill" aria-label="Kill bot" disabled={saving||isDemo||state.stopped} onClick={()=>control('stop')}><Square size={13}/><span>Kill bot</span></button></div></div>
 {notice&&<div className="toast">{notice}</div>}{liquidateOpen&&<div className="backdrop" onClick={()=>setLiquidateOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>PAPER TRADING</small><h2>Liquidate holdings?</h2></div><button className="icon-btn" onClick={()=>setLiquidateOpen(false)}><X size={17}/></button></div><p>This cancels pending buys, pauses trading and sells all paper holdings for USDT at the next fresh bid. The sale may realise a loss.</p><div className="modal-actions"><button onClick={()=>setLiquidateOpen(false)}>Cancel</button><button className="liquidate-confirm" disabled={saving} onClick={liquidate}>{saving?'Liquidating…':'Liquidate paper holdings'}</button></div></section></div>}{capsOpen&&<div className="backdrop" onClick={()=>setCapsOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>BOT SAFETY</small><h2>Risk limits</h2></div><button className="icon-btn" onClick={()=>setCapsOpen(false)}><X size={17}/></button></div><p>Set account caps for float, order size, daily loss and API spend.</p>{([['floatUsdt','Trading float'],['maxOrderUsdt','Maximum order size'],['dailyLossStopUsdt','Daily loss stop'],['dailyApiSpendUsd','Daily API spend']] as const).map(([key,label])=><label className="cap" key={key}><span>{label}</span><input type="number" min="0" step=".01" value={caps[key]} onChange={e=>setCaps(c=>({...c,[key]:Number(e.target.value)}))}/></label>)}<div className="modal-actions"><button onClick={()=>setCapsOpen(false)}>Cancel</button><button className="save" disabled={saving||isDemo} onClick={()=>control('set-caps')}>{saving?'Saving…':'Save limits'}</button></div>{isDemo&&<small className="hint">Connect the backend to change risk limits.</small>}</section></div>}
 </div>
}
function PortfolioChart({points,range,onRange,loading,currentValue}:{points:PortfolioPoint[];range:PortfolioRange;onRange:(range:PortfolioRange)=>void;loading:boolean;currentValue:number}){
 const now=Date.now(),duration:Record<PortfolioRange,number>={'15m':15*60_000,'1h':60*60_000,'24h':24*60*60_000,'7d':7*24*60*60_000,all:0};
 const start=range==='all'?(points[0]?.ts??now-60_000):now-duration[range];
 const end=range==='all'?(points[points.length-1]?.ts??now):now;
 const visible=points.filter(point=>point.ts>=start&&point.ts<=end);
 const rawMin=visible.length?Math.min(...visible.map(point=>point.valueUsdt)):0,rawMax=visible.length?Math.max(...visible.map(point=>point.valueUsdt)):1;
 const pad=Math.max((rawMax-rawMin)*.16,Math.max(rawMax,1)*.002),min=rawMin-pad,max=rawMax+pad,span=end-start||1;
 const x=(ts:number)=>42+(ts-start)/span*704,y=(value:number)=>16+(max-value)/(max-min)*116;
 const coords=visible.map(point=>[x(point.ts),y(point.valueUsdt)] as const);
 const line=coords.map(([px,py],i)=>`${i?'L':'M'} ${px.toFixed(1)} ${py.toFixed(1)}`).join(' ');
 const area=coords.length?`${line} L ${coords[coords.length-1][0].toFixed(1)} 136 L ${coords[0][0].toFixed(1)} 136 Z`:'';
 const axisLabel=(ts:number)=>range==='15m'||range==='1h'?new Date(ts).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}):new Date(ts).toLocaleDateString('en-AU',{day:'numeric',month:'short'});
 return <section className="panel portfolio-chart"><div className="chart-heading"><div><h2>Portfolio value</h2><small>{visible.length?`${visible.length} data points · ${range==='all'?'All available history':`Past ${range}`}`:loading?'Loading history…':'No history available for this range'}</small></div><div className="chart-tools"><strong>{cash(currentValue)}</strong><div className="range-tabs" role="group" aria-label="Portfolio graph time range">{portfolioRanges.map(item=><button key={item} className={range===item?'selected':''} aria-pressed={range===item} onClick={()=>onRange(item)}>{item}</button>)}</div></div></div>
  {visible.length?<div className="chart-wrap"><svg className="chart-svg" viewBox="0 0 760 166" role="img" aria-label={`Portfolio value over ${range}`} preserveAspectRatio="none"><defs><linearGradient id="portfolio-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2c9c6d" stopOpacity=".16"/><stop offset="1" stopColor="#2c9c6d" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=>{const yy=16+i*38.66,value=max-i*(max-min)/3;return <g key={i}><line x1="42" x2="746" y1={yy} y2={yy} className="chart-gridline"/><text x="36" y={yy+3} textAnchor="end" className="chart-y-label">{cash(value)}</text></g>})}{coords.length>1&&<path d={area} fill="url(#portfolio-fill)"/>}{coords.length>1&&<path d={line} className="chart-line"/>}{coords.length===1&&<circle cx={coords[0][0]} cy={coords[0][1]} r="4" className="chart-point"/>}{coords.length>1&&<circle cx={coords[coords.length-1][0]} cy={coords[coords.length-1][1]} r="3.5" className="chart-point"/>}{Array.from({length:5},(_,i)=>{const ts=start+(end-start)*i/4;return <text key={i} x={42+704*i/4} y="157" textAnchor={i===0?'start':i===4?'end':'middle'} className="chart-x-label">{axisLabel(ts)}</text>})}</svg></div>:<div className="chart-empty">{loading?'Fetching portfolio history…':'Portfolio history will appear here when the backend has recorded data.'}</div>}
 </section>
}
function Metric({label,value,icon,positive,large}:{label:string;value:string;icon:React.ReactNode;positive?:boolean;large?:boolean}){return <article className={`metric ${large?'large':''}`}><div><span>{label}</span>{icon}</div><b className={positive===undefined?'':positive?'positive':'negative'}>{value}</b>{large&&<small>USDT account value</small>}</article>}
function PanelTitle({title,meta,action,onAction}:{title:string;meta?:string;action?:string;onAction?:()=>void}){return <div className="panel-title"><div><h2>{title}</h2>{meta&&<small>{meta}</small>}</div>{action&&<button onClick={onAction}>{action} ↗</button>}</div>}
function Param({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
