import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Bot, Clock3, Coins, Gauge, Pause, Play, Radio, RefreshCw, ShieldAlert, Square, Terminal, Wallet, X } from 'lucide-react';
import type { ControlAction, DashboardState } from './types';

type PortfolioPoint = { ts: number; valueUsdt: number };
type PortfolioRange = '15m' | '1h' | '24h' | '7d' | 'all';
const portfolioRanges: PortfolioRange[] = ['15m', '1h', '24h', '7d', 'all'];
const mergePoints = (...groups: PortfolioPoint[][]) => {
 const byTime = new Map<number, PortfolioPoint>();
 groups.flat().forEach(point => { if (Number.isFinite(point.ts) && Number.isFinite(point.valueUsdt)) byTime.set(point.ts, point); });
 return [...byTime.values()].sort((a,b)=>a.ts-b.ts);
};

const demo: DashboardState = {
  mode:'paper', paused:false, stopped:false, liquidationPending:false,
  health:{feedConnected:false,lastTickTs:0,jevReady:false,reviewerReady:false},
  balances:{availableUsdt:10,holdings:[],portfolioUsdt:10,realisedPnlUsdt:0,unrealisedPnlUsdt:0,feesUsdt:0,drawdownPercent:0,openPositions:0},
  usage:{jev:{inputTokens:0,outputTokens:0,costUsd:0,requests:0},openai:{inputTokens:0,outputTokens:0,costUsd:0,requests:0},totalCostUsd:0},
  caps:{floatUsdt:10,maxOrderUsdt:.2,dailyLossStopUsdt:1,dailyApiSpendUsd:1,maxHoldSeconds:900,maxPositions:1},
  strategy:{version:1,entryConfidence:.85,continuationProbability:.8,reversalExitProbability:.75,costBufferBps:15,targetHoldSeconds:120,positionFraction:.02,selectedSymbols:[]},
  latestReview:'',openOrders:[],recentTrades:[],recentEvents:[],skippedReasons:{},metrics:{decisions:0,approved:0,avgDecisionLatencyMs:0},candidateCount:0,updatedAt:Date.now()
};
const cash=(n:number,code='USDT',minimumFractionDigits=2)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:code==='USDT'?'USD':code,minimumFractionDigits,maximumFractionDigits:minimumFractionDigits===2?2:6}).format(n).replace('US$','＄');
const reasonLabels:Record<string,string>={paused:'Bot paused',position_limit:'Maximum open positions reached',daily_loss_stop:'Daily loss limit reached',api_spend_stop:'Daily API spend limit reached',stale_data:'Market or JEV data is stale',stale_book:'Order book data is stale',symbol_unavailable:'Symbol unavailable for trading',not_selected:'Symbol is outside the selected strategy set',invalid_book:'Invalid bid and ask prices',liquidity:'Liquidity or spread requirements not met',insufficient_usdt:'Insufficient USDT for order',below_exchange_minimum:'Order is below the exchange minimum',jev_threshold:'Standard JEV gate not met',exploratory_jev_threshold:'Exploratory JEV gate not met',unproven_net_edge:'Net trading edge is not established',jev_error:'JEV assessment failed'};
const reasonLabel=(reason:string)=>reasonLabels[reason]??reason.replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const num=(n:number,d=2)=>new Intl.NumberFormat('en-AU',{maximumFractionDigits:d}).format(n);
const ago=(ts:number)=>{const s=Math.max(0,Math.floor((Date.now()-ts)/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};

export default function App(){
 const [state,setState]=useState<DashboardState>(demo),[connected,setConnected]=useState(false),[isDemo,setDemo]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[capsOpen,setCapsOpen]=useState(false),[liquidateOpen,setLiquidateOpen]=useState(false),[caps,setCaps]=useState(demo.caps),[now,setNow]=useState(Date.now());
 const [maxOrderInput,setMaxOrderInput]=useState(String(demo.caps.maxOrderUsdt)),[maxPositionsInput,setMaxPositionsInput]=useState(String(demo.caps.maxPositions));
 const capsDirty=useRef(false);
 const [view,setView]=useState<'Overview'|'Markets'|'Positions'|'Activity log'|'Settings'>('Overview'),[startingUsdt,setStartingUsdt]=useState(demo.caps.floatUsdt),[credentials,setCredentials]=useState({JEV_API_KEY:'',OPENAI_API_KEY:'',BINANCE_API_KEY:'',BINANCE_API_SECRET:''}),[credentialStatus,setCredentialStatus]=useState<Record<string,boolean>>({}),[configSaving,setConfigSaving]=useState(false);
 const [portfolioRange,setPortfolioRange]=useState<PortfolioRange>('24h'),[portfolioPoints,setPortfolioPoints]=useState<PortfolioPoint[]>([]),[portfolioLoading,setPortfolioLoading]=useState(true);
 useEffect(()=>{let alive=true;const apply=(data:string)=>{try{const x=JSON.parse(data) as DashboardState;if(x?.balances&&x?.health){setState(x);if(!capsDirty.current){setCaps(x.caps);setMaxOrderInput(String(x.caps.maxOrderUsdt));setMaxPositionsInput(String(x.caps.maxPositions))}setDemo(false);setConnected(true);setPortfolioPoints(points=>mergePoints(points,[{ts:x.updatedAt,valueUsdt:x.balances.portfolioUsdt}]))}}catch{}};const poll=()=>fetch('/api/state').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>apply(JSON.stringify(x))).catch(()=>alive&&setConnected(false));poll();const es=new EventSource('/api/events');es.addEventListener('state',e=>apply((e as MessageEvent).data));es.onopen=()=>alive&&setConnected(true);es.onerror=()=>alive&&setConnected(false);const p=window.setInterval(poll,15000),t=window.setInterval(()=>setNow(Date.now()),10000);return()=>{alive=false;es.close();clearInterval(p);clearInterval(t)}},[]);
 useEffect(()=>{let alive=true;const pollPortfolio=()=>fetch(`/api/portfolio?range=${portfolioRange}`).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{points:PortfolioPoint[]}>}).then(data=>{if(alive&&Array.isArray(data.points)){const history=mergePoints(data.points);setPortfolioPoints(previous=>{const latest=previous[previous.length-1];const liveTail=latest&&(!history.length||latest.ts>history[history.length-1].ts)?[latest]:[];return mergePoints(history,liveTail)});setPortfolioLoading(false)}}).catch(()=>{if(alive)setPortfolioLoading(false)});setPortfolioLoading(true);pollPortfolio();const timer=window.setInterval(pollPortfolio,20000);return()=>{alive=false;clearInterval(timer)}},[portfolioRange]);
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(x=>setCredentialStatus(x.credentials??{})).catch(()=>{});},[]);
 const age=useMemo(()=>Math.max(0,Math.floor((now-state.updatedAt)/1000)),[now,state.updatedAt]);
 const health=[state.health.feedConnected?'Feed online':'Feed offline',state.health.jevReady?'JEV ready':'JEV unavailable',state.health.reviewerReady?'Reviewer ready':'Reviewer unavailable'];
 const validMaxPositions=Number.isInteger(Number(maxPositionsInput))&&Number(maxPositionsInput)>=1&&Number(maxPositionsInput)<=50;
 async function control(action:ControlAction,extra?:{startingUsdt?:number;caps?:Partial<DashboardState['caps']>}){
  setSaving(true);setNotice('');
  try{
   const body=action==='set-caps'?{action,caps:extra?.caps}:action==='start-paper'?{action,startingUsdt:extra?.startingUsdt}:{action};
   const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
   const next=await r.json() as DashboardState & {error?:string};
   if(!r.ok)throw Error(next.error??`Request failed (${r.status})`);
   {
    setState(next);setCaps(next.caps);setMaxOrderInput(String(next.caps.maxOrderUsdt));setMaxPositionsInput(String(next.caps.maxPositions));capsDirty.current=false;
   }
   if(action==='set-caps')setCapsOpen(false);
   setNotice(action==='start-paper'?'Paper run started':action==='restart'?'Trading restarted. The existing paper balance is retained.':action==='set-caps'?'Risk limits updated':`Bot ${action==='stop'?'stopped':action==='pause'?'paused':'resumed'}`);
  }catch(e){setNotice(e instanceof Error?e.message:'Control request failed')}
  finally{setSaving(false);setTimeout(()=>setNotice(''),3500)}
 }
 function cancelCaps(){capsDirty.current=false;setCaps(state.caps);setMaxOrderInput(String(state.caps.maxOrderUsdt));setMaxPositionsInput(String(state.caps.maxPositions));setCapsOpen(false)}
 function changeMaxOrder(value:string){capsDirty.current=true;setMaxOrderInput(value);setCaps(c=>({...c,maxOrderUsdt:Number(value)}))}
 function changeMaxPositions(value:string){capsDirty.current=true;setMaxPositionsInput(value);setCaps(c=>({...c,maxPositions:Number(value)}))}
 async function saveCredentials(){setConfigSaving(true);setNotice('');try{const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credentials})});const result=await r.json();if(!r.ok)throw Error(result.error??'Could not save credentials');setCredentialStatus(result.credentials??{});setCredentials({JEV_API_KEY:'',OPENAI_API_KEY:'',BINANCE_API_KEY:'',BINANCE_API_SECRET:''});setNotice('Credentials saved. Provider status has updated.')}catch(e){setNotice(e instanceof Error?e.message:'Could not save credentials')}finally{setConfigSaving(false);setTimeout(()=>setNotice(''),3500)}}
 async function liquidate(){setSaving(true);setNotice('');try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'liquidate'})});if(!r.ok)throw Error('Liquidation request failed');const next=await r.json() as DashboardState;setState(next);setNotice(next.liquidationPending?'Liquidation queued until a fresh bid arrives':'Paper holdings sold for USDT; trading paused')}catch(e){setNotice(e instanceof Error?e.message:'Liquidation request failed')}finally{setSaving(false);setLiquidateOpen(false);setTimeout(()=>setNotice(''),3500)}}
 const service=(title:string,s:DashboardState['usage']['jev'])=><div className="service-row"><div className="service-title"><i>{title==='JEV'?'J':<Bot size={16}/>}</i><div><b>{title}</b><small><span className={`dot ${title==='JEV'?(state.health.jevReady?'green':''):(state.health.reviewerReady?'green':'')}`}/>{title==='JEV'?(state.paused?'Calls paused':state.health.jevReady?'Ready':'Offline'):(state.paused?'Calls paused':state.health.reviewerReady?'Ready':'Offline')}</small></div></div><div><small>Requests</small><b>{s.requests}</b></div><div><small>Tokens in / out</small><b>{num(s.inputTokens,0)} / {num(s.outputTokens,0)}</b></div><div><small>Spend</small><b>{cash(s.costUsd,'USD',4)}</b></div></div>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Activity size={18}/></span><span><b>JEV trading bot</b><small>TRADING OPS</small></span></div><div className="workspace"><span className="workspace-icon">J</span><span><b>JEV trading bot</b><small>Personal workspace</small></span></div><div className="nav-label">MONITOR</div><nav>{([ ["Overview",<Gauge size={17}/>],["Markets",<Activity size={17}/>],["Positions",<Coins size={17}/>],["Activity log",<Terminal size={17}/>],["Settings",<ShieldAlert size={17}/>] ] as const).map(([name,icon])=><button key={name} title={name} aria-label={name} className={view===name?"active":""} onClick={()=>setView(name)}>{icon}{name}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-status"><span className={`dot ${connected?'green':''}`}/><span><b>{connected?'API connected':'Waiting for API'}</b><small>{isDemo?'Default config only':'Live state stream'}</small></span></div><div className="user"><span className="avatar">HS</span><span><b>Henry Simpson</b><small>Operator</small></span></div></div></aside>
 <main className="main"><header className="topbar"><div>Workspace <i>/</i> <b>{view}</b></div><div className="top-actions"><span className="stream"><span className={`dot ${connected?'green':''}`}/>{connected?'Streaming':'Reconnecting'} · {age}s</span><button className="icon-btn" onClick={()=>fetch('/api/state').then(r=>r.json()).then(setState).catch(()=>setConnected(false))}><RefreshCw size={16}/></button><span className="avatar">HS</span></div></header><div className="content">
 {isDemo&&<div className="demo"><Radio size={15}/><b>Backend offline</b><span>Showing default configuration. Live balances, usage and controls need the backend.</span></div>}
 {view==='Overview'&&<><section className="heading"><div><small className="eyebrow">TRADING OPERATIONS</small><h1>Trading overview</h1><p>Portfolio performance and bot health at a glance.</p></div><div className="head-pills"><span className="pill mode"><i/> {state.mode} mode</span><span className="pill health"><i/> {health.join(' · ')}</span></div></section>
 <section className="metrics"><Metric label="Portfolio value" value={cash(state.balances.portfolioUsdt)} icon={<Wallet size={16}/>} large/><Metric label="Realised P&L" value={cash(state.balances.realisedPnlUsdt)} positive={state.balances.realisedPnlUsdt>=0} icon={<Activity size={16}/>}/><Metric label="Unrealised P&L" value={cash(state.balances.unrealisedPnlUsdt)} positive={state.balances.unrealisedPnlUsdt>=0} icon={<Activity size={16}/>}/><Metric label="Fees paid" value={cash(state.balances.feesUsdt)} icon={<Coins size={16}/>}/><Metric label="Drawdown" value={`${num(state.balances.drawdownPercent)}%`} icon={<ShieldAlert size={16}/>}/></section>
 <PortfolioChart points={portfolioPoints} range={portfolioRange} onRange={setPortfolioRange} loading={portfolioLoading} currentValue={state.balances.portfolioUsdt}/>
 <div className="grid"><section className="panel"><PanelTitle title="Balances & holdings" meta={`${state.balances.holdings.length+1} ${state.balances.holdings.length?'assets':'asset'}`}/><div className="holding row"><span className="token usdt">₮</span><span><b>USDT</b><small>Available balance</small></span><span className="right"><b>{num(state.balances.availableUsdt)}</b><small>Stablecoin float</small></span></div>{state.balances.holdings.map(h=><div className="holding row" key={h.symbol}><span className="token">{h.symbol.slice(0,1)}</span><span><b>{h.symbol}</b><small>{num(h.quantity,6)} units · entry {cash(h.entryPrice)}</small></span><span className="right"><b>{cash(h.valueUsdt)}</b><small>Held {num(h.ageSeconds/60,1)}m{state.positionPlans?.[h.symbol]&&` · stop ${cash(state.positionPlans[h.symbol].stopBid,'USDT',4)}`}</small></span></div>)}<div className="holding-foot"><span>Open positions</span><b>{state.balances.openPositions} / {state.caps.maxPositions}</b></div></section>
 <section className="panel"><PanelTitle title="API usage & spend" meta="Current day"/>{service('JEV',state.usage.jev)}{service('OpenAI',state.usage.openai)}<div className="total-spend"><span>Total API spend</span><b>{cash(state.usage.totalCostUsd,'USD',4)}</b><small>Daily cap {cash(state.caps.dailyApiSpendUsd,'USD')}</small></div></section>
 <section className="panel"><PanelTitle title="Open orders" meta={`${state.openOrders.length} active`}/><div className="table-wrap"><table><thead><tr><th>Market</th><th>Side</th><th>Price</th><th>Amount</th><th>Placed</th></tr></thead><tbody>{state.openOrders.length?state.openOrders.map(o=><tr key={o.id}><td><b>{o.symbol}</b><small>{o.id}</small></td><td><em className={o.side.toLowerCase()}>{o.side}</em></td><td>{cash(o.price)}</td><td>{num(o.quantity,6)}</td><td>{ago(o.ts)}</td></tr>):<tr><td colSpan={5} className="empty">No open orders</td></tr>}</tbody></table></div></section>
 <section className="panel review"><PanelTitle title="Latest review" meta="Suggestions only"/><div className="review-copy"><span className="review-icon"><Bot size={17}/></span><p>{state.latestReview||'No review has been recorded yet.'}</p></div><small className="review-foot"><Clock3 size={13}/> Updated {ago(state.updatedAt)}</small></section>
 <section className="panel"><PanelTitle title="Recent trades" meta={`${state.recentTrades.length} latest`}/><p className="trade-note">Net P/L on each sale includes its share of the entry fee and the exit fee. API costs are excluded.</p><div className="table-wrap"><table><thead><tr><th>Market</th><th>Side</th><th>Price</th><th>Notional</th><th>Fee</th><th>Net P/L</th><th>Time</th></tr></thead><tbody>{state.recentTrades.length?state.recentTrades.map(t=><tr key={t.id}><td><b>{t.symbol}</b><small>{t.reason}</small></td><td><em className={t.side.toLowerCase()}>{t.side}</em></td><td>{cash(t.price)}</td><td>{cash(t.notionalUsdt)}</td><td>{cash(t.feeUsdt)}</td><td className={t.netPnlUsdt===undefined?'':t.netPnlUsdt>=0?'pnl-positive':'pnl-negative'}>{t.side==='BUY'?'Entry':t.netPnlUsdt===undefined?'Unavailable':`${t.netPnlUsdt>0?'+':''}${cash(t.netPnlUsdt,'USDT',4)}`}</td><td>{ago(t.ts)}</td></tr>):<tr><td colSpan={7} className="empty">No recent trades</td></tr>}</tbody></table></div></section>
 {state.experiment&&<section className="panel"><PanelTitle title="Strategy comparisons" meta="Shadow positions, separate from your balance"/><div className="review-copy"><p>JEV reassesses positions every {state.experiment.reassessmentSeconds} seconds. Normal volatility is allowed, the stop never widens, and total holding time is capped at {state.experiment.maxHoldSeconds/60} minutes. New entries wait for positive measured outcomes after costs. API calls stop while paused.</p></div><div className="table-wrap"><table><thead><tr><th>Exit approach</th><th>Covered outcomes</th><th>Mean net return</th></tr></thead><tbody>{state.experiment.comparisons.filter(x=>x.variant!=='calibration').map(x=><tr key={x.variant}><td>{({fixed_time:'Fixed time',volatility:'Volatility stop',jev_volatility:'JEV + volatility',passive_fixed:'Passive entry + fixed time'} as Record<string,string>)[x.variant]??x.variant}</td><td>{x.covered} / {x.completed}</td><td>{x.meanNetBps===null?'Awaiting outcomes':`${num(x.meanNetBps,1)} bps`}</td></tr>)}</tbody></table></div><div className="review-copy"><small>{state.experiment.shadowPositions} shadow candidates being tracked. Missing quotes and unfilled passive orders are excluded from mean returns. These comparisons do not establish profitability.</small></div></section>}
 <section className="panel strategy"><PanelTitle title="Strategy & risk" meta={`Version ${state.strategy.version}`} action="Edit limits" onAction={()=>setCapsOpen(true)}/><div className="strategy-name"><span className="strategy-icon"><Activity size={17}/></span><div><b>Active strategy</b><small>{state.strategy.selectedSymbols.join(' · ')||'All eligible monitored markets'}</small></div></div><div className="params"><Param label="Minimum setup score" value="2 / 4"/><Param label="Continuation" value={num(state.strategy.continuationProbability*100,0)+'%'}/><Param label="Reversal exit" value={num(state.strategy.reversalExitProbability*100,0)+'%'}/><Param label="Cost buffer" value={`${num(state.strategy.costBufferBps,0)} bps`}/><Param label="Planned hold" value="30 to 120 sec"/><Param label="Position fraction" value={`${num(state.strategy.positionFraction*100,1)}%`}/></div><div className="risk"><b>Paper execution</b><div className="inline-cap"><span>Maximum order</span><input aria-label="Maximum paper order in USDT" type="number" min="0.01" step="0.01" value={maxOrderInput} disabled={isDemo} onChange={e=>changeMaxOrder(e.target.value)}/><button className="save-button" disabled={saving||isDemo||!Number.isFinite(Number(maxOrderInput))||Number(maxOrderInput)<=0} onClick={()=>control('set-caps',{caps:{maxOrderUsdt:Number(maxOrderInput)}})}>{saving?'Saving…':'Save'}</button></div><div className="inline-cap"><span>Maximum open positions</span><input aria-label="Maximum open paper positions" type="number" min="1" max="50" step="1" value={maxPositionsInput} disabled={isDemo} onChange={e=>changeMaxPositions(e.target.value)}/><button className="save-button" disabled={saving||isDemo||!validMaxPositions} onClick={()=>control('set-caps',{caps:{maxPositions:Number(maxPositionsInput)}})}>{saving?'Saving…':'Save'}</button></div><small>Effective order limit {cash(Math.max(0,Math.min(caps.maxOrderUsdt,state.caps.floatUsdt*state.strategy.positionFraction,state.balances.availableUsdt)))}. New entries require positive prior outcomes after costs. JEV reassesses holdings every three seconds within the API budget.</small><b>Risk limits</b><span>Float <strong>{cash(state.caps.floatUsdt)}</strong></span><span>Daily loss stop <strong>{cash(state.caps.dailyLossStopUsdt)}</strong></span><span>Max positions <strong>{state.caps.maxPositions}</strong></span><span>Max hold <strong>{num((state.experiment?.maxHoldSeconds??state.caps.maxHoldSeconds)/60,0)} min</strong></span><span>Daily API spend <strong>{cash(state.caps.dailyApiSpendUsd,'USD')}</strong></span></div></section>
 <section className="panel"><PanelTitle title="Skipped signals" meta="Current session"/><div className="skips">{Object.entries(state.skippedReasons).length?Object.entries(state.skippedReasons).map(([why,count])=><div key={why}><span><X size={12}/>{reasonLabel(why)}</span><b>{count}</b></div>):<p className="empty">No skipped signals recorded.</p>}</div><div className="gate-diagnostics"><b>Signal diagnostics</b>{Object.entries(state.jevGateFailures??{}).length?Object.entries(state.jevGateFailures??{}).map(([gate,count])=><span key={gate}>{gate.replace(/[A-Z]/g,m=>` ${m.toLowerCase()}`)} <strong>{count}</strong></span>):<small>Assessments will appear here as JEV responds.</small>}</div><div className="skip-note">{state.metrics.approved} orders approved of {state.metrics.decisions} decisions · {Math.round(state.metrics.avgDecisionLatencyMs)}ms average · {state.candidateCount} available markets · {state.monitoredMarketCount??0} monitored</div></section></div>
 <footer>JEV trading bot · State age {age}s · {isDemo?'Backend offline':'Connected backend'}</footer></>}
 {view==='Markets'&&<section className="page-view panel"><PanelTitle title="Markets" meta={`${state.candidateCount} USDT markets available`}/><p>Market scanning is active when the feed is online. Recent symbols seen by the bot:</p><div className="table-wrap"><table><thead><tr><th>Market</th><th>Last action</th><th>Time</th></tr></thead><tbody>{state.recentTrades.length?state.recentTrades.map(t=><tr key={t.id}><td>{t.symbol}</td><td>{t.side} · {t.reason}</td><td>{ago(t.ts)}</td></tr>):<tr><td colSpan={3} className="empty">No market trades recorded yet.</td></tr>}</tbody></table></div></section>}
 {view==='Positions'&&<section className="page-view panel"><PanelTitle title="Positions" meta={`${state.balances.openPositions} open`}/>{state.balances.holdings.length?state.balances.holdings.map(h=><div className="holding row" key={h.symbol}><span><b>{h.symbol}</b><small>{num(h.quantity,6)} units at {cash(h.entryPrice)}</small></span><span className="right"><b>{cash(h.valueUsdt)}</b><small>{num(h.ageSeconds/60,0)} minutes held</small></span></div>):<p className="empty">No open positions.</p>}</section>}
 {view==='Activity log'&&<section className="page-view panel"><PanelTitle title="Activity log" meta={`${state.recentEvents.length} recent events`}/>{state.recentEvents.length?state.recentEvents.map((event,i)=>{const e=event as {ts?:number;kind?:string;symbol?:string;message?:string};return <div className="event-row" key={`${e.ts}-${i}`}><b>{e.kind??'Event'}</b><span>{e.symbol??e.message??''}</span><small>{e.ts?ago(e.ts):''}</small></div>}):<p className="empty">No events recorded.</p>}</section>}
 {view==='Settings'&&<div className="settings-grid"><section className="panel settings-panel"><PanelTitle title="API credentials" meta="Stored locally"/><p>Enter API keys here. Saved values stay in the local .env file and are never shown again.</p>{([['JEV_API_KEY','JEV API key'],['OPENAI_API_KEY','OpenAI API key'],['BINANCE_API_KEY','Binance API key'],['BINANCE_API_SECRET','Binance API secret']] as const).map(([key,label])=><label className="cap" key={key}><span>{label}<small>{credentialStatus[key]?'Configured':'Not configured'}</small></span><input type="password" autoComplete="new-password" value={credentials[key]} placeholder={credentialStatus[key]?'Saved, enter a new value to replace':''} onChange={e=>setCredentials(c=>({...c,[key]:e.target.value}))}/></label>)}<div className="modal-actions"><button className="save" disabled={configSaving||!Object.values(credentials).some(Boolean)} onClick={saveCredentials}>{configSaving?'Saving…':'Save credentials'}</button></div></section><section className="panel settings-panel"><PanelTitle title="Trading mode" meta={state.mode.toUpperCase()}/><p>Live trading is unavailable in this build. The Binance order adapter is not connected to the running bot, so mode changes cannot place live orders.</p><button className="mode-disabled" disabled>Live mode unavailable</button><h3>Paper account</h3><p>Choose a starting USDT balance and start a fresh paper run. Pause trading first. Starting again requires no open position or order.</p><label className="cap"><span>Starting balance (USDT)</span><input type="number" min="0.01" max="1000000" step="0.01" value={startingUsdt} onChange={e=>setStartingUsdt(Number(e.target.value))}/></label><button className="save-button" disabled={saving||isDemo||state.stopped||!state.paused||!!state.balances.openPositions||state.openOrders.length>0||!Number.isFinite(startingUsdt)||startingUsdt<=0} onClick={()=>control('start-paper',{startingUsdt})}>{saving?'Starting…':'Start paper run'}</button>{state.stopped&&<small className="hint">The bot is stopped and must be restarted before a new run.</small>}</section></div> }
 </div></main>
 <div className="dock"><div><span className={`dot ${state.health.feedConnected?'green':''}`}/><span><b>Bot controls</b><small>{state.liquidationPending?'Liquidation pending':state.stopped?(state.balances.openPositions?'Closing holdings':'Stopped'):state.paused?'Paused, API calls stopped':state.mode==='live'?'Live trading':'Paper trading'}</small></span></div><div className="dock-buttons"><button className={state.paused?'resume':''} aria-label={state.paused?'Resume trading':'Pause trading'} disabled={saving||isDemo||state.stopped||state.liquidationPending} onClick={()=>control(state.paused?'resume':'pause')}>{state.paused?<Play size={14}/>:<Pause size={14}/>}<span>{state.paused?'Resume trading':'Pause trading'}</span></button><button className="liquidate" aria-label="Liquidate paper holdings" disabled={saving||isDemo||state.liquidationPending||(!state.balances.holdings.length&&!state.openOrders.length)} onClick={()=>setLiquidateOpen(true)}><Coins size={14}/><span>Liquidate</span></button><button className="kill" aria-label={state.stopped?'Restart trading':'Kill bot'} disabled={saving||isDemo||state.liquidationPending||(state.stopped&&state.balances.openPositions>0)} onClick={()=>control(state.stopped?'restart':'stop')}>{state.stopped?<Play size={13}/>:<Square size={13}/>}<span>{state.stopped?'Restart trading':'Kill bot'}</span></button></div></div>
 {notice&&<div className="toast">{notice}</div>}{liquidateOpen&&<div className="backdrop" onClick={()=>setLiquidateOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>PAPER TRADING</small><h2>Liquidate holdings?</h2></div><button className="icon-btn" onClick={()=>setLiquidateOpen(false)}><X size={17}/></button></div><p>This cancels pending buys, pauses trading and sells all paper holdings for USDT at the next fresh bid. The sale may realise a loss.</p><div className="modal-actions"><button onClick={()=>setLiquidateOpen(false)}>Cancel</button><button className="liquidate-confirm" disabled={saving} onClick={liquidate}>{saving?'Liquidating…':'Liquidate paper holdings'}</button></div></section></div>}{capsOpen&&<div className="backdrop" onClick={cancelCaps}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>BOT SAFETY</small><h2>Risk limits</h2></div><button className="icon-btn" onClick={cancelCaps}><X size={17}/></button></div><p>Set paper trading caps for float, order size, open positions, daily loss and API spend.</p>{([['floatUsdt','Trading float'],['maxOrderUsdt','Maximum order size'],['maxPositions','Maximum open positions (1 to 50)'],['dailyLossStopUsdt','Daily loss stop'],['dailyApiSpendUsd','Daily API spend']] as const).map(([key,label])=><label className="cap" key={key}><span>{label}</span><input type="number" min={key==='maxPositions'?'1':'0.01'} max={key==='maxPositions'?'50':undefined} step={key==='maxPositions'?'1':'.01'} value={key==='maxOrderUsdt'?maxOrderInput:key==='maxPositions'?maxPositionsInput:caps[key]} onChange={e=>{capsDirty.current=true;if(key==='maxOrderUsdt')changeMaxOrder(e.target.value);else if(key==='maxPositions')changeMaxPositions(e.target.value);else setCaps(c=>({...c,[key]:Number(e.target.value)}))}}/></label>)}<div className="modal-actions"><button onClick={cancelCaps}>Cancel</button><button className="save" disabled={saving||isDemo||!validMaxPositions||Object.values(caps).some(value=>!Number.isFinite(value)||value<=0)} onClick={()=>control('set-caps',{caps:{floatUsdt:caps.floatUsdt,maxOrderUsdt:Number(maxOrderInput),maxPositions:Number(maxPositionsInput),dailyLossStopUsdt:caps.dailyLossStopUsdt,dailyApiSpendUsd:caps.dailyApiSpendUsd}})}>{saving?'Saving…':'Save limits'}</button></div>{isDemo&&<small className="hint">Connect the backend to change risk limits.</small>}</section></div>}
 </div>
}
function PortfolioChart({points,range,onRange,loading,currentValue}:{points:PortfolioPoint[];range:PortfolioRange;onRange:(range:PortfolioRange)=>void;loading:boolean;currentValue:number}){
 const now=Date.now(),duration:Record<PortfolioRange,number>={'15m':15*60_000,'1h':60*60_000,'24h':24*60*60_000,'7d':7*24*60*60_000,all:0};
 const wrapRef=useRef<HTMLDivElement>(null),svgRef=useRef<SVGSVGElement>(null);
 const [plotWidth,setPlotWidth]=useState(900),[selectedIndex,setSelectedIndex]=useState<number|null>(null);
 useEffect(()=>{const node=wrapRef.current;if(!node)return;const observer=new ResizeObserver(entries=>{const width=entries[0]?.contentRect.width;if(width)setPlotWidth(width);});observer.observe(node);return()=>observer.disconnect()},[]);
 useEffect(()=>setSelectedIndex(null),[range]);
 const start=range==='all'?(points[0]?.ts??now-60_000):now-duration[range];
 const end=range==='all'?(points[points.length-1]?.ts??now):now;
 const visible=points.filter(point=>point.ts>=start&&point.ts<=end);
 const rawMin=visible.length?Math.min(...visible.map(point=>point.valueUsdt)):0,rawMax=visible.length?Math.max(...visible.map(point=>point.valueUsdt)):1;
 const pad=rawMax===rawMin?Math.max(Math.abs(rawMax)*.005,.01):Math.max((rawMax-rawMin)*.12,.01),min=rawMin-pad,max=rawMax+pad,span=end-start||1;
 const width=plotWidth,height=270,left=92,right=20,top=20,bottom=38,plotW=width-left-right,plotH=height-top-bottom;
 const x=(ts:number)=>left+(ts-start)/span*plotW,y=(value:number)=>top+(max-value)/(max-min)*plotH;
 const coords=visible.map(point=>[x(point.ts),y(point.valueUsdt)] as const);
 const line=coords.map(([px,py],i)=>`${i?'L':'M'} ${px.toFixed(1)} ${py.toFixed(1)}`).join(' ');
 const area=coords.length?`${line} L ${coords[coords.length-1][0].toFixed(1)} ${top+plotH} L ${coords[0][0].toFixed(1)} ${top+plotH} Z`:'';
 const axisLabel=(ts:number)=>range==='15m'||range==='1h'||range==='24h'?new Date(ts).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}):new Date(ts).toLocaleDateString('en-AU',{day:'numeric',month:'short'});
 const formatPointTime=(ts:number)=>new Date(ts).toLocaleString('en-AU',{dateStyle:'medium',timeStyle:'medium'});
 const selected=selectedIndex===null?null:visible[selectedIndex]??null;
 const pointX=selected?x(selected.ts):0,pointY=selected?y(selected.valueUsdt):0;
 const tooltipLeft=Math.max(8,Math.min(width-220,pointX-100)),tooltipTop=pointY<100?pointY+14:pointY-76;
 const pointChange=selected&&selectedIndex!==null&&selectedIndex>0?selected.valueUsdt-visible[selectedIndex-1]!.valueUsdt:null;
 const nearest=(clientX:number)=>{const svg=svgRef.current;if(!svg||!visible.length)return;const rect=svg.getBoundingClientRect(),localX=(clientX-rect.left)/rect.width*width;let best=0,distance=Infinity;coords.forEach(([px],i)=>{const next=Math.abs(px-localX);if(next<distance){best=i;distance=next}});setSelectedIndex(best)};
 const move=(event:React.PointerEvent<SVGSVGElement>)=>nearest(event.clientX);
 const key=(event:React.KeyboardEvent<SVGSVGElement>)=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();setSelectedIndex(index=>Math.max(0,Math.min(visible.length-1,(index??0)+(event.key==='ArrowRight'?1:-1))))}else if(event.key==='Escape')setSelectedIndex(null)};
 return <section className="panel portfolio-chart"><div className="chart-heading"><div><h2>Portfolio value</h2><small>{visible.length?`${visible.length} data points · ${range==='all'?'All current run history':`Past ${range} · Current run`}`:loading?'Loading history…':'No history available for this range'}</small></div><div className="chart-tools"><strong>{cash(currentValue)}</strong><div className="range-tabs" role="group" aria-label="Portfolio graph time range">{portfolioRanges.map(item=><button key={item} className={range===item?'selected':''} aria-pressed={range===item} onClick={()=>onRange(item)}>{item}</button>)}</div></div></div>
  {visible.length?<div className="chart-wrap" ref={wrapRef}><svg ref={svgRef} className="chart-svg" viewBox={`0 0 ${width} ${height}`} role="group" tabIndex={0} aria-label={`Portfolio value over ${range}. Use left and right arrow keys to inspect data points.`} onFocus={()=>setSelectedIndex(index=>index??0)} onPointerMove={move} onPointerLeave={()=>setSelectedIndex(null)} onPointerDown={event=>{if(event.pointerType==='touch')nearest(event.clientX)}} onKeyDown={key}><defs><linearGradient id="portfolio-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2c9c6d" stopOpacity=".16"/><stop offset="1" stopColor="#2c9c6d" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=>{const yy=top+i*plotH/3,value=max-i*(max-min)/3;return <g key={i}><line x1={left} x2={width-right} y1={yy} y2={yy} className="chart-gridline"/><text x={left-10} y={yy+4} textAnchor="end" className="chart-y-label">{cash(value)}</text></g>})}{coords.length>1&&<path d={area} fill="url(#portfolio-fill)"/>}{coords.length>1&&<path d={line} className="chart-line"/>}{coords.map(([cx,cy],i)=><circle key={`${visible[i]!.ts}`} cx={cx} cy={cy} r={i===selectedIndex?5:1.5} className={`chart-point ${i===selectedIndex?'active':''}`}/>)}{selected&&<g className="chart-crosshair"><line x1={pointX} x2={pointX} y1={top} y2={top+plotH}/><circle cx={pointX} cy={pointY} r="5"/></g>}{Array.from({length:5},(_,i)=>{const ts=start+(end-start)*i/4;return <text key={i} x={left+plotW*i/4} y={height-8} textAnchor={i===0?'start':i===4?'end':'middle'} className="chart-x-label">{axisLabel(ts)}</text>})}</svg>{selected&&<div className="chart-tooltip" style={{left:tooltipLeft,top:Math.max(5,Math.min(height-70,tooltipTop))}} role="status"><b>{cash(selected.valueUsdt)}</b><span>{formatPointTime(selected.ts)}</span><small>{pointChange===null?'First point in this run':`${pointChange>=0?'+':''}${cash(pointChange)} from previous point`}</small></div>}</div>:<div className="chart-empty">{loading?'Fetching portfolio history…':'Portfolio history will appear here when the backend has recorded data.'}</div>}
 </section>
}
function Metric({label,value,icon,positive,large}:{label:string;value:string;icon:React.ReactNode;positive?:boolean;large?:boolean}){return <article className={`metric ${large?'large':''}`}><div><span>{label}</span>{icon}</div><b className={positive===undefined?'':positive?'positive':'negative'}>{value}</b>{large&&<small>USDT account value</small>}</article>}
function PanelTitle({title,meta,action,onAction}:{title:string;meta?:string;action?:string;onAction?:()=>void}){return <div className="panel-title"><div><h2>{title}</h2>{meta&&<small>{meta}</small>}</div>{action&&<button onClick={onAction}>{action} ↗</button>}</div>}
function Param({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
